// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikqeazzyrzurrjoeoxov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrcWVhenp5cnp1cnJqb2VveG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjI4MjMsImV4cCI6MjA2NjYzODgyM30.YEHt9-S8g2FFd7VaJEuzvU-cZc0nAx-SwlWpCQZiEL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});